apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-nginx
  template:
    metadata:
      labels:
        app: service-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  type: ClusterIP
  selector:
    app: service-nginx
  ports:
  - port: 8080
    targetPort: 80
