apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-new
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-new
  template:
    metadata:
      labels:
        app: nginx-new
    spec:
      containers:
      - name: nginx-new-v1
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-new
spec:
  type: NodePort
  selector:
    app: nginx-new
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30010
