apiVersion: v1
kind: Pod
metadata:
  name: new-nginx
  labels:
    name: nginx
    version: v1
    tipe: test
  namespace: test
spec:
  containers:
  - name: new-nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "10Mi"
        cpu: "10m"
    ports:
      - containerPort: 80
